hero_ids = ['1:Anti-Mage', '2:Axe', '3:Bane', '4:Bloodseeker', '5:Crystal Maiden', '6:Drow Ranger', '7:Earthshaker',
            '8:Juggernaut', '9:Mirana', '11:Shadow Fiend', '10:Morphling', '12:Phantom Lancer', '13:Puck', '14:Pudge',
            '15:Razor', '16:Sand King', '17:Storm Spirit', '18:Sven', '19:Tiny', '20:Vengeful Spirit', '21:Windranger',
            '22:Zeus', '23:Kunkka', '25:Lina', '31:Lich', '26:Lion', '27:Shadow Shaman', '28:Slardar', '29:Tidehunter',
            '30:Witch Doctor', '32:Riki', '33:Enigma', '34:Tinker', '35:Sniper', '36:Necrophos', '37:Warlock',
            '38:Beastmaster', '39:Queen of Pain', '40:Venomancer', '41:Faceless Void', '42:Wraith King',
            '43:Death Prophet', '44:Phantom Assassin', '45:Pugna', '46:Templar Assassin', '47:Viper', '48:Luna',
            '49:Dragon Knight', '50:Dazzle', '51:Clockwerk', '52:Leshrac', "53:Nature's Prophet", '54:Lifestealer',
            '55:Dark Seer', '56:Clinkz', '57:Omniknight', '58:Enchantress', '59:Huskar', '60:Night Stalker',
            '61:Broodmother', '62:Bounty Hunter', '63:Weaver', '64:Jakiro', '65:Batrider', '66:Chen', '67:Spectre',
            '69:Doom', '68:Ancient Apparition', '70:Ursa', '71:Spirit Breaker', '72:Gyrocopter', '73:Alchemist',
            '74:Invoker', '75:Silencer', '76:Outworld Destroyer', '77:Lycan', '78:Brewmaster', '79:Shadow Demon',
            '80:Lone Druid', '81:Chaos Knight', '82:Meepo', '83:Treant Protector', '84:Ogre Magi', '85:Undying',
            '86:Rubick', '87:Disruptor', '88:Nyx Assassin', '89:Naga Siren', '90:Keeper of the Light', '91:Io',
            '92:Visage', '93:Slark', '94:Medusa', '95:Troll Warlord', '96:Centaur Warrunner', '97:Magnus',
            '98:Timbersaw', '99:Bristleback', '100:Tusk', '101:Skywrath Mage', '102:Abaddon', '103:Elder Titan',
            '104:Legion Commander', '106:Ember Spirit', '107:Earth Spirit', '109:Terrorblade', '110:Phoenix',
            '111:Oracle', '105:Techies', '112:Winter Wyvern', '113:Arc Warden', '108:Underlord', '114:Monkey King',
            '120:Pangolier', '119:Dark Willow', '121:Grimstroke', '129:Mars', '126:Void Spirit', '128:Snapfire',
            '123:Hoodwink', '135:Dawnbreaker', '136:Marci', '137:Primal Beast', '138:Muerta']

hero_names_alphabetically = ['Abaddon', 'Alchemist', 'Ancient Apparition', 'Anti-Mage', 'Arc Warden', 'Axe', 'Bane',
                             'Batrider',
                             'Beastmaster', 'Bloodseeker', 'Bounty Hunter', 'Brewmaster', 'Bristleback', 'Broodmother',
                             'Centaur Warrunner', 'Chaos Knight', 'Chen', 'Clinkz', 'Clockwerk', 'Crystal Maiden',
                             'Dark Seer',
                             'Dark Willow', 'Dawnbreaker', 'Dazzle', 'Death Prophet', 'Disruptor', 'Doom',
                             'Dragon Knight',
                             'Drow Ranger', 'Earth Spirit', 'Earthshaker', 'Elder Titan', 'Ember Spirit', 'Enchantress',
                             'Enigma',
                             'Faceless Void', 'Grimstroke', 'Gyrocopter', 'Hoodwink', 'Huskar', 'Invoker', 'Io',
                             'Jakiro',
                             'Juggernaut', 'Keeper of the Light', 'Kunkka', 'Legion Commander', 'Leshrac', 'Lich',
                             'Lifestealer',
                             'Lina', 'Lion', 'Lone Druid', 'Luna', 'Lycan', 'Magnus', 'Marci', 'Mars', 'Medusa',
                             'Meepo', 'Mirana',
                             'Monkey King', 'Morphling', 'Muerta', 'Naga Siren', 'Nature Prophet', 'Necrophos',
                             'Night Stalker',
                             'Nyx Assassin', 'Ogre Magi', 'Omniknight', 'Oracle', 'Outworld Destroyer', 'Pangolier',
                             'Phantom Assassin', 'Phantom Lancer', 'Phoenix', 'Primal Beast', 'Puck', 'Pudge', 'Pugna',
                             'Queen of Pain', 'Razor', 'Riki', 'Rubick', 'Sand King', 'Shadow Demon', 'Shadow Fiend',
                             'Shadow Shaman', 'Silencer', 'Skywrath Mage', 'Slardar', 'Slark', 'Snapfire', 'Sniper',
                             'Spectre',
                             'Spirit Breaker', 'Storm Spirit', 'Sven', 'Techies', 'Techies Arcane', 'Templar Assassin',
                             'Terrorblade',
                             'Tidehunter', 'Timbersaw', 'Tinker', 'Tiny', 'Treant Protector', 'Troll Warlord', 'Tusk',
                             'Underlord',
                             'Undying', 'Ursa', 'Vengeful Spirit', 'Venomancer', 'Viper', 'Visage', 'Void Spirit',
                             'Warlock',
                             'Weaver', 'Windranger', 'Winter Wyvern', 'Witch Doctor', 'Wraith King', 'Zeus']

carry = ['1:Anti-Mage', '4:Bloodseeker', '6:Drow Ranger', '8:Juggernaut', '11:Shadow Fiend', '10:Morphling',
         '12:Phantom Lancer', '18:Sven', '32:Riki', '35:Sniper', '41:Faceless Void', '42:Wraith King',
         '44:Phantom Assassin', '48:Luna', '49:Dragon Knight', '54:Lifestealer', '63:Weaver', '67:Spectre', '70:Ursa',
         '72:Gyrocopter', '73:Alchemist', '81:Chaos Knight', '82:Meepo', '89:Naga Siren', '93:Slark', '94:Medusa',
         '95:Troll Warlord', '102:Abaddon', '109:Terrorblade', '114:Monkey King', '138:Muerta']

mid = ['7:Earthshaker', '11:Shadow Fiend', '13:Puck', '14:Pudge', '15:Razor', '17:Storm Spirit', '19:Tiny',
       '21:Windranger', '22:Zeus', '23:Kunkka', '25:Lina', '34:Tinker', '35:Sniper', '36:Necrophos', '39:Queen of Pain',
       '43:Death Prophet', '46:Templar Assassin', '47:Viper', '49:Dragon Knight', '50:Dazzle', '52:Leshrac',
       '59:Huskar', '74:Invoker', '76:Outworld Destroyer', '80:Lone Druid', '82:Meepo', '90:Keeper of the Light',
       '92:Visage', '98:Timbersaw', '101:Skywrath Mage', '106:Ember Spirit', '107:Earth Spirit', '113:Arc Warden',
       '114:Monkey King', '120:Pangolier', '126:Void Spirit', '137:Primal Beast']

offlane = ['2:Axe', '14:Pudge', '15:Razor', '16:Sand King', '23:Kunkka', '28:Slardar', '29:Tidehunter', '36:Necrophos',
           '38:Beastmaster', '42:Wraith King', '43:Death Prophet', '47:Viper', '49:Dragon Knight', '52:Leshrac',
           '55:Dark Seer', '57:Omniknight', '60:Night Stalker', '61:Broodmother', '65:Batrider', '69:Doom',
           '71:Spirit Breaker', '77:Lycan', '78:Brewmaster', '80:Lone Druid', '81:Chaos Knight', '84:Ogre Magi',
           '96:Centaur Warrunner', '97:Magnus', '98:Timbersaw', '99:Bristleback', '103:Elder Titan',
           '104:Legion Commander', '108:Underlord', '129:Mars', '126:Void Spirit', '135:Dawnbreaker',
           '137:Primal Beast']

support = ['3:Bane', '5:Crystal Maiden', '7:Earthshaker', '9:Mirana', '14:Pudge', '19:Tiny', '20:Vengeful Spirit',
           '21:Windranger', '22:Zeus', '25:Lina', '31:Lich', '26:Lion', '27:Shadow Shaman', '30:Witch Doctor',
           '32:Riki', '33:Enigma', '35:Sniper', '37:Warlock', '40:Venomancer', '45:Pugna', '50:Dazzle', '51:Clockwerk',
           "53:Nature's Prophet", '55:Dark Seer', '56:Clinkz', '57:Omniknight', '58:Enchantress', '62:Bounty Hunter',
           '64:Jakiro', '65:Batrider', '66:Chen', '68:Ancient Apparition', '71:Spirit Breaker', '72:Gyrocopter',
           '74:Invoker', '75:Silencer', '79:Shadow Demon', '83:Treant Protector', '84:Ogre Magi', '85:Undying',
           '86:Rubick', '87:Disruptor', '88:Nyx Assassin', '90:Keeper of the Light', '91:Io', '97:Magnus',
           '100:Tusk', '101:Skywrath Mage', '102:Abaddon', '103:Elder Titan', '107:Earth Spirit', '109:Terrorblade',
           '110:Phoenix', '111:Oracle', '105:Techies', '112:Winter Wyvern', '114:Monkey King', '119:Dark Willow',
           '121:Grimstroke', '128:Snapfire', '123:Hoodwink', '136:Marci', '137:Primal Beast']

hard_support = ['3:Bane', '5:Crystal Maiden', '20:Vengeful Spirit', '31:Lich', '26:Lion', '27:Shadow Shaman',
                '30:Witch Doctor', '37:Warlock', '40:Venomancer', '45:Pugna', '50:Dazzle', '51:Clockwerk',
                '57:Omniknight', '58:Enchantress', '64:Jakiro', '66:Chen', '68:Ancient Apparition',
                '74:Invoker', '75:Silencer', '79:Shadow Demon', '83:Treant Protector', '85:Undying', '87:Disruptor',
                '91:Io', '100:Tusk', '101:Skywrath Mage', '110:Phoenix', '111:Oracle', '105:Techies',
                '112:Winter Wyvern', '121:Grimstroke', '123:Hoodwink']

aoe_control = ['2:Axe', '5:Crystal Maiden', '7:Earthshaker',
               '11:Shadow Fiend', '13:Puck', '16:Sand King', '17:Storm Spirit', '18:Sven', '19:Tiny',
               '23:Kunkka', '31:Lich', '26:Lion', '29:Tidehunter',
               '30:Witch Doctor', '33:Enigma', '37:Warlock',
               '41:Faceless Void', '42:Wraith King',
               '47:Viper', '48:Luna',
               '49:Dragon Knight', '50:Dazzle', '51:Clockwerk', '52:Leshrac', "53:Nature's Prophet",
               '55:Dark Seer', '59:Huskar', '60:Night Stalker',
               '64:Jakiro', '65:Batrider',
               '69:Doom', '68:Ancient Apparition', '71:Spirit Breaker', '72:Gyrocopter',
               '74:Invoker', '78:Brewmaster',
               '80:Lone Druid', '82:Meepo', '83:Treant Protector', '84:Ogre Magi',
               '86:Rubick', '87:Disruptor', '88:Nyx Assassin', '89:Naga Siren', '90:Keeper of the Light',
               '94:Medusa', '96:Centaur Warrunner', '97:Magnus',
               '100:Tusk', '103:Elder Titan', '110:Phoenix',
               '105:Techies', '112:Winter Wyvern', '108:Underlord',
               '120:Pangolier', '119:Dark Willow', '121:Grimstroke', '129:Mars', '128:Snapfire',
               '123:Hoodwink', '135:Dawnbreaker']

initiation = ['2:Axe', '7:Earthshaker', '11:Shadow Fiend', '13:Puck', '14:Pudge',
              '15:Razor', '16:Sand King', '17:Storm Spirit', '18:Sven', '19:Tiny', '20:Vengeful Spirit',
              '23:Kunkka', '25:Lina', '26:Lion', '27:Shadow Shaman', '28:Slardar', '29:Tidehunter',
              '32:Riki', '33:Enigma', '34:Tinker', '37:Warlock', '39:Queen of Pain', '49:Dragon Knight', '50:Dazzle',
              '51:Clockwerk', '52:Leshrac', "53:Nature's Prophet", '55:Dark Seer', '59:Huskar', '60:Night Stalker',
              '65:Batrider', '67:Spectre', '69:Doom', '71:Spirit Breaker', '74:Invoker', '76:Outworld Destroyer',
              '77:Lycan', '78:Brewmaster', '81:Chaos Knight', '82:Meepo', '83:Treant Protector', '86:Rubick',
              '87:Disruptor', '89:Naga Siren', '93:Slark', '96:Centaur Warrunner', '97:Magnus',
              '98:Timbersaw', '100:Tusk', '103:Elder Titan', '104:Legion Commander', '106:Ember Spirit',
              '107:Earth Spirit', '110:Phoenix', '105:Techies', '112:Winter Wyvern', '113:Arc Warden',
              '108:Underlord', '114:Monkey King', '120:Pangolier', '129:Mars', '126:Void Spirit', '135:Dawnbreaker',
              '137:Primal Beast']

game_changers = ['7:Earthshaker', '17:Storm Spirit', '29:Tidehunter', '30:Witch Doctor', '33:Enigma', '37:Warlock',
                 '41:Faceless Void', '55:Dark Seer', '75:Silencer', '87:Disruptor', '89:Naga Siren',
                 '97:Magnus', '110:Phoenix', '112:Winter Wyvern']

bkb_control = ['2:Axe', '3:Bane', '4:Bloodseeker', '13:Puck', '14:Pudge', '20:Vengeful Spirit', '28:Slardar',
               '33:Enigma', '37:Warlock', '38:Beastmaster', '41:Faceless Void', '51:Clockwerk', '55:Dark Seer',
               '59:Huskar', '65:Batrider', '69:Doom', '68:Ancient Apparition', '71:Spirit Breaker',
               '83:Treant Protector', '87:Disruptor', '95:Troll Warlord', '97:Magnus', '100:Tusk', '103:Elder Titan',
               '104:Legion Commander', '110:Phoenix', '112:Winter Wyvern', '135:Dawnbreaker', '137:Primal Beast']

magic = ['5:Crystal Maiden', '7:Earthshaker', '11:Shadow Fiend', '13:Puck', '14:Pudge', '16:Sand King',
         '17:Storm Spirit', '22:Zeus', '23:Kunkka', '25:Lina', '31:Lich', '26:Lion', '34:Tinker', '36:Necrophos',
         '39:Queen of Pain', '43:Death Prophet', '47:Viper', '50:Dazzle', '52:Leshrac', '59:Huskar', '64:Jakiro',
         '65:Batrider', '69:Doom', '68:Ancient Apparition', '71:Spirit Breaker', '74:Invoker', '75:Silencer',
         '76:Outworld Destroyer', '78:Brewmaster', '84:Ogre Magi', '88:Nyx Assassin', '90:Keeper of the Light',
         '96:Centaur Warrunner', '98:Timbersaw', '101:Skywrath Mage', '106:Ember Spirit', '107:Earth Spirit',
         '105:Techies', '112:Winter Wyvern', '113:Arc Warden', '120:Pangolier', '119:Dark Willow', '128:Snapfire',
         '135:Dawnbreaker', '136:Marci', '137:Primal Beast', '138:Muerta']

phys = ['1:Anti-Mage', '4:Bloodseeker', '6:Drow Ranger', '7:Earthshaker', '8:Juggernaut', '11:Shadow Fiend',
        '10:Morphling', '12:Phantom Lancer', '13:Puck', '15:Razor', '18:Sven', '19:Tiny', '21:Windranger',
        '25:Lina', '28:Slardar', '32:Riki', '35:Sniper', '41:Faceless Void', '42:Wraith King',
        '44:Phantom Assassin', '46:Templar Assassin', '47:Viper', '48:Luna', '49:Dragon Knight', "53:Nature's Prophet",
        '54:Lifestealer', '56:Clinkz', '58:Enchantress', '59:Huskar', '60:Night Stalker', '61:Broodmother', '63:Weaver',
        '67:Spectre', '70:Ursa', '72:Gyrocopter', '73:Alchemist', '77:Lycan', '80:Lone Druid', '81:Chaos Knight',
        '82:Meepo', '89:Naga Siren', '92:Visage', '93:Slark', '94:Medusa', '95:Troll Warlord', '97:Magnus',
        '99:Bristleback', '102:Abaddon', '103:Elder Titan', '104:Legion Commander', '106:Ember Spirit',
        '109:Terrorblade', '113:Arc Warden', '114:Monkey King', '129:Mars', '126:Void Spirit', '128:Snapfire',
        '135:Dawnbreaker', '136:Marci']

tower_damage = ['1:Anti-Mage', '4:Bloodseeker', '6:Drow Ranger', '7:Earthshaker', '8:Juggernaut', '11:Shadow Fiend',
                '10:Morphling', '12:Phantom Lancer', '18:Sven', '19:Tiny', '21:Windranger',
                '25:Lina', '27:Shadow Shaman', '35:Sniper', '37:Warlock', '38:Beastmaster', '39:Queen of Pain',
                '41:Faceless Void', '42:Wraith King', '43:Death Prophet', '44:Phantom Assassin', '45:Pugna',
                '46:Templar Assassin', '47:Viper', '48:Luna', '49:Dragon Knight', '52:Leshrac', "53:Nature's Prophet",
                '54:Lifestealer', '56:Clinkz', '59:Huskar', '60:Night Stalker', '61:Broodmother', '63:Weaver',
                '67:Spectre', '70:Ursa', '72:Gyrocopter', '73:Alchemist', '74:Invoker', '77:Lycan', '78:Brewmaster',
                '80:Lone Druid', '81:Chaos Knight', '82:Meepo', '89:Naga Siren', '92:Visage', '93:Slark', '94:Medusa',
                '95:Troll Warlord', '99:Bristleback', '102:Abaddon', '103:Elder Titan', '104:Legion Commander',
                '106:Ember Spirit', '109:Terrorblade', '105:Techies', '113:Arc Warden', '114:Monkey King',
                '126:Void Spirit', '128:Snapfire', '138:Muerta']

safe_pushing = ['1:Anti-Mage', '13:Puck', '17:Storm Spirit', '21:Windranger', '23:Kunkka', '25:Lina',
                '27:Shadow Shaman', '34:Tinker', '35:Sniper', '39:Queen of Pain', "53:Nature's Prophet",
                '56:Clinkz', '61:Broodmother', '71:Spirit Breaker', '74:Invoker', '77:Lycan', '80:Lone Druid',
                '82:Meepo', '83:Treant Protector', '89:Naga Siren', '106:Ember Spirit', '113:Arc Warden',
                '114:Monkey King', '126:Void Spirit']

sustain = ['5:Crystal Maiden', '14:Pudge', '30:Witch Doctor', '34:Tinker', '36:Necrophos', '37:Warlock',
           '38:Beastmaster', '45:Pugna', '50:Dazzle', '54:Lifestealer', '57:Omniknight', '58:Enchantress', '63:Weaver',
           '66:Chen', '83:Treant Protector', '85:Undying', '89:Naga Siren', '90:Keeper of the Light', '91:Io',
           '93:Slark', '102:Abaddon', '104:Legion Commander', '109:Terrorblade', '110:Phoenix', '111:Oracle',
           '112:Winter Wyvern', '135:Dawnbreaker', '136:Marci']

damage_dealers = ['1:Anti-Mage', '4:Bloodseeker', '6:Drow Ranger', '7:Earthshaker',
                  '8:Juggernaut', '11:Shadow Fiend', '10:Morphling', '12:Phantom Lancer', '13:Puck',
                  '15:Razor', '17:Storm Spirit', '18:Sven', '21:Windranger',
                  '22:Zeus', '25:Lina', '28:Slardar',
                  '30:Witch Doctor', '34:Tinker', '35:Sniper',
                  '39:Queen of Pain', '41:Faceless Void', '42:Wraith King',
                  '44:Phantom Assassin', '46:Templar Assassin', '47:Viper', '48:Luna',
                  '49:Dragon Knight', '52:Leshrac', '54:Lifestealer',
                  '56:Clinkz', '58:Enchantress', '59:Huskar', '60:Night Stalker',
                  '61:Broodmother', '63:Weaver', '67:Spectre',
                  '69:Doom', '70:Ursa', '71:Spirit Breaker', '72:Gyrocopter', '73:Alchemist',
                  '74:Invoker', '76:Outworld Destroyer', '77:Lycan', '78:Brewmaster',
                  '80:Lone Druid', '81:Chaos Knight', '82:Meepo',
                  '89:Naga Siren', '93:Slark', '94:Medusa', '95:Troll Warlord', '96:Centaur Warrunner',
                  '98:Timbersaw', '99:Bristleback', '101:Skywrath Mage', '102:Abaddon', '104:Legion Commander',
                  '106:Ember Spirit', '107:Earth Spirit', '109:Terrorblade', '113:Arc Warden', '114:Monkey King',
                  '129:Mars', '126:Void Spirit',
                  '135:Dawnbreaker', '136:Marci', '138:Muerta']
